name: HW1

on:
  push:
    branches: [ hw-1 ]

env:
  BUILD_TYPE: Debug

jobs:

  Build:
    runs-on: ubuntu-latest
    container: mans02/c-hw-image

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS=on

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}
        run: |
          ls -la