name: HW1

on:
  push:
    branches: [ hw-1 ]

jobs:

  Build:
    runs-on: ubuntu-latest
    container: mans02/c-hw-image

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: make configure

      - name: Build
        run: make build

  Test:
    runs-on: ubuntu-latest
    container: mans02/c-hw-image
    needs: [Build]

    steps:
      - uses: actions/checkout@v3

      - name: Launch Tests
        run ./build/tests/flight_lib