name: HW1

on:
  push:
    branches: [ hw-1 ]

jobs:

  Build:
    runs-on: ubuntu-latest
    container: mans02/c-hw-image

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: make configure

      - name: Build
        run: make build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_dir
          path: build/

  Test:
    runs-on: ubuntu-latest
    container: mans02/c-hw-image
    needs: [Build]

    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build_dir
          path: build/

      - name: Launch tests
        run: make test

      - name: Check code coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/coverage.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
  Lint:
    runs-on: ubuntu-latest
    container: mans02/c-hw-image

    steps:
      - uses: actions/checkout@v3

      - name: Lint
        run: make lint

  Format:
    runs-on: ubuntu-latest
    container: mans02/c-hw-image

    steps:
      - uses: actions/checkout@v3

      - name: Format
        run: make format