name: HW1

on:
  push:
    branches: [ hw-1 ]

env:
  BUILD_TYPE: Debug

jobs:

  Build:
    runs-on: ubuntu-latest
    container: mans02/c-hw-image

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
      - run: |
          cmake -DBUILD_TESTS=on -B build
          cd build
          cmake --build .
          ls -la

#      - uses: actions/upload-artifact@v3
#        with:
#          path: ${{github.workspace}}/build
#
#      - name: Upload artifacts

#
#      - name: Test
#        run: |
#          cd ../..
#          ls -la